fixtures:
    symlinks:
      motd: "#{source_dir}"
    repositories:
      stdlib:
        repo: https://github.com/puppetlabs/puppetlabs-stdlib.git
        ref: v7.0.1
      concat:
        repo: https://github.com/puppetlabs/puppetlabs-concat.git
        ref: v7.0.1
    forge_modules:
