fixtures:
    symlinks:
      motd: "#{source_dir}"
    repositories:
      stdlib:
        repo: https://github.com/puppetlabs/puppetlabs-stdlib.git
        ref: v6.2.0
      concat:
        repo: https://github.com/puppetlabs/puppetlabs-concat.git
        ref: v6.2.0
    forge_modules:
